spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://svar-employee.cb51j9rilsps.us-east-2.rds.amazonaws.com:3306/Employee?useSSL=false
        username: root
        password: 17121999
        hikari:
            initialization-fail-timeout: 0        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create